### ISSUE TITLE
Cache model list api might not be returning  all models

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/api-gorest#2]
I am not so sure if there are only 3500 models after https://s3.amazonaws.com/geneontology-public/gocam/gocam-models.json
The live api seems to return correct number https://api.geneontology.cloud/models/

Maybe the cache not updating

![image](https://user-images.githubusercontent.com/2273929/132577871-d6296204-75e1-43bb-9ad3-afddf751fe70.png)

The live Api getModels 

![image](https://user-images.githubusercontent.com/2273929/132578508-f4d2b6ef-16c8-4f9e-8e2f-d22a477f1873.png)

**Comment by kltm** [comment]
This is currently being addressed by geneontology/web-gocam#20
